Name: Faq
Version: 0.1.0
Link: https://github.com/Webiny/Faq
Description: Simple app for creating FAQ articles and categories
Author:
    Name: Webiny LTD
    Email: info@webiny.com
    Link: https://www.webiny.com
